version: "3.9"

name: practica-php
services:
  db:
    image: mysql:5.7
    container_name: notes_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: notes_app
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: notes_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

  php:
    image: php:8.2-apache
    container_name: notes_php
    volumes:
      - ./demo:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db